---
permalink: audit/accessing-audit-log-file.html 
sidebar: sidebar 
keywords: storagegrid, audit, log, log file, access, accessing 
summary: 'Le partage d"audit contient le fichier audit.log actif et tous les fichiers journaux d"audit compressés. Pour faciliter l"accès aux journaux d"audit, vous pouvez configurer l"accès client aux partages d"audit pour NFS. Vous pouvez également accéder aux fichiers journaux d"audit directement à partir de la ligne de commande du nœud d"administration.' 
---
= Accéder au fichier journal d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le partage d'audit contient le partage actif `audit.log` fichier et tous les fichiers journaux d'audit compressés. Pour accéder facilement aux journaux d'audit, vous pouvez le faire link:../admin/configuring-audit-client-access.html["Configurer l'accès client d'audit pour NFS"]. Vous pouvez également accéder aux fichiers journaux d'audit directement à partir de la ligne de commande du nœud d'administration.

.Avant de commencer
* Vous devez disposer d'autorisations d'accès spécifiques.
* Vous devez avoir le `Passwords.txt` fichier.
* Vous devez connaître l'adresse IP d'un nœud d'administration.


.Étapes
. Connectez-vous à un nœud d'administration :
+
.. Saisissez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Accédez au répertoire contenant les fichiers journaux d'audit :
+
`cd /var/local/audit/export`

. Afficher le fichier journal d'audit actuel ou enregistré, selon les besoins.

