---
settings:
  name: StorageGRID 11.7
  downlevel: true
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents StorageGRID 11.7
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/release-notes/index.html"
  - title: Commencez
    entries:
    - section: primer
    - section: network
    - title: Démarrage rapide pour StorageGRID
      url: "/primer/quick-start.html"
  - title: Installation et mise à niveau
    entries:
    - section: installconfig
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Configurez et gérez
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Utiliser StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Surveiller et résoudre les problèmes
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Maintenance
    entries:
    - section: expand
    - section: maintain
    - section: commonhardware
    - section: sg6100
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Activez StorageGRID
    url: "/storagegrid-enable.html"
  - title: Autres versions
    url: "/earlier-versions.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Notes de mise à jour
      url: "/release-notes/index.html"
    - title: Quoi de neuf
      url: "/upgrade/whats-new.html"
    - title: Découvrez StorageGRID
      url: "/primer/index.html"
    - title: Instructions de mise en réseau
      url: "/network/index.html"
    - title: Démarrage rapide de StorageGRID
      url: "/primer/quick-start.html"
  - title: Installer et entretenir le matériel
    links:
    - title: Installez et déployez des appliances
      url: "/installconfig/index.html"
    - title: Maintenance des appliances
      url: "/maintain/index.html"
  - title: Installer et mettre à niveau le logiciel
    links:
    - title: Installez Red Hat Enterprise Linux ou CentOS
      url: "/rhel/index.html"
    - title: Installez Ubuntu ou Debian
      url: "/ubuntu/index.html"
    - title: Installez VMware
      url: "/vmware/index.html"
    - title: Mise à niveau du logiciel
      url: "/upgrade/index.html"
  - title: Configurer la grille
    links:
    - title: Administrer StorageGRID
      url: "/admin/index.html"
    - title: Gestion des objets avec ILM
      url: "/ilm/index.html"
    - title: Durcissement du système
      url: "/harden/index.html"
    - title: Configuration de StorageGRID pour FabricPool
      url: "/fabricpool/index.html"
  - title: Gérer les objets
    links:
    - title: Utilisez un compte de locataire
      url: "/tenant/index.html"
    - title: UTILISEZ L'API REST S3
      url: "/s3/index.html"
    - title: Utiliser l'API REST de Swift (obsolète)
      url: "/swift/index.html"
  - title: Surveillance et maintenance
    links:
    - title: Superviser
      url: "/monitor/index.html"
    - title: Résoudre les problèmes
      url: "/troubleshoot/index.html"
    - title: Examiner les journaux d'audit
      url: "/audit/index.html"
    - title: Développez votre grille
      url: "/expand/index.html"
    - title: Restauration et maintenance
      url: "/maintain/index.html"
  - title: Démonstrations et didacticiels
    links:
    - title: Découvrez comment activer StorageGRID
      url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
    - title: Vidéothèque StorageGRID
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
    - title: Services de formation NetApp
      url: https://www.netapp.com/support-and-training/netapp-university/
  - title: Ressources supplémentaires
    links:
    - title: Page de support StorageGRID
      url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
    - title: Matrice d'interopérabilité NetApp (IMT)
      url: https://imt.netapp.com/matrix/#welcome
    - title: Base de connaissances StorageGRID
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
    - title: Blog NetApp
      url: https://netapp.com/blog/
    - title: Communauté NetApp
      url: https://community.netapp.com/
  - title: Autres versions
    links:
    - title: Documentation StorageGRID 11.6
      url: https://docs.netapp.com/us-en/storagegrid-116/index.html
    - title: Documentation sur StorageGRID 11.5
      url: https://docs.netapp.com/us-en/storagegrid-115/index.html
    - title: Documentation sur StorageGRID 11.4
      url: https://docs.netapp.com/sgws-114/index.jsp
    - title: Documentation sur StorageGRID 11.3
      url: https://docs.netapp.com/sgws-113/index.jsp
    - title: Documentation sur StorageGRID 11.2
      url: https://docs.netapp.com/sgws-112/index.jsp
