---
settings:
  name: StorageGRID 11.7
  search: storagegrid-enable,storagegrid-117
  downlevel: true
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    hide_language_selector: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents StorageGRID 11.7
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/release-notes/index.html"
  - title: Commencez
    entries:
    - section: primer
    - section: network
    - title: Démarrage rapide pour StorageGRID
      url: "/primer/quick-start.html"
  - title: Installation et mise à niveau
    entries:
    - section: installconfig
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Configurez et gérez
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Utiliser StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Surveiller et résoudre les problèmes
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Maintenance
    entries:
    - section: expand
    - section: maintain
    - section: commonhardware
    - section: sg6100
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Activez StorageGRID
    url: "/storagegrid-enable.html"
  - title: Autres versions
    url: "/earlier-versions.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
