---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Avant de mettre à niveau un système StorageGRID, vous devez vérifier que celui-ci est prêt à effectuer la mise à niveau. Vous devez vous assurer que le système fonctionne normalement et que tous les nœuds de la grille sont opérationnels. 
---
= Vérifier l'état du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau un système StorageGRID, vous devez vérifier que celui-ci est prêt à effectuer la mise à niveau. Vous devez vous assurer que le système fonctionne normalement et que tous les nœuds de la grille sont opérationnels.

.Étapes
. Connectez-vous au Grid Manager à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
. Recherchez et résolvez les alertes actives.
. Confirmez qu'aucune tâche de grille en conflit n'est active ou en attente.
+
.. Sélectionnez *SUPPORT* > *Outils* > *topologie de grille*.
.. Sélectionnez *_site_* > *_primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
Les tâches d'évaluation de la gestion du cycle de vie des informations (IDME) sont les seules tâches de grille pouvant être exécutées simultanément avec la mise à niveau logicielle.

.. Si d'autres tâches de grille sont actives ou en attente, attendez qu'elles aient terminé ou lâchés leur verrouillage.
+

NOTE: Contactez le support technique si une tâche ne se termine pas ou ne relâche pas son verrouillage.



. Reportez-vous à la section link:../network/internal-grid-node-communications.html["Communications internes sur les nœuds de la grille"] et link:../network/external-communications.html["Communications externes"] Pour vous assurer que tous les ports requis pour StorageGRID 11.7 sont ouverts avant la mise à niveau.
+
Les éléments suivants link:../network/internal-grid-node-communications.html#storagegrid-internal-ports["ports internes"] Doit être ouvert avant la mise à niveau vers StorageGRID 11.7 :

+
[cols="1a,2a"]
|===
| Port | Description 


 a| 
1055

8011

10342
 a| 
Utilisé pour le protocole de cognement des contrôles de pare-feu.

Avant de procéder à la mise à niveau, vérifiez que ce port est ouvert entre tous les nœuds de la grille du réseau.



 a| 
18086
 a| 
Port TCP utilisé pour le nouveau service LDR.

Avant de procéder à la mise à niveau, vérifiez que ce port est ouvert de tous les nœuds de grid à tous les nœuds de stockage.

|===



IMPORTANT: Si vous avez ouvert des ports de pare-feu personnalisés, vous êtes averti au cours de la vérification préalable de la mise à niveau. Vous devez contacter le support technique avant de procéder à la mise à niveau.
