---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Vous devez comprendre en quoi votre système StorageGRID sera affecté lors de la mise à niveau. 
---
= Quel est l'impact de votre système pendant la mise à niveau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez comprendre en quoi votre système StorageGRID sera affecté lors de la mise à niveau.



== Les mises à niveau de StorageGRID ne générant pas de perturbation

Le système StorageGRID peut ingérer et récupérer les données depuis les applications client tout au long du processus de mise à niveau. Si vous approuvez la mise à niveau de tous les nœuds du même type (par exemple, nœuds de stockage), les nœuds sont arrêtés un par un. Ainsi, il n'y a pas de temps lorsque tous les nœuds de grid ou tous les nœuds de grid d'un certain type sont indisponibles.

Pour assurer une disponibilité continue, vérifiez que votre règle ILM contient des règles qui spécifient le stockage de plusieurs copies de chaque objet. Vous devez également vous assurer que tous les clients S3 ou Swift externes sont configurés pour envoyer des demandes à l'un des éléments suivants :

* Adresse IP virtuelle d'un groupe haute disponibilité (HA)
* Équilibreur de charge tiers haute disponibilité
* Plusieurs nœuds de passerelle pour chaque client
* Plusieurs nœuds de stockage pour chaque client




== Le micrologiciel de l'appliance est mis à niveau

Pendant la mise à niveau de StorageGRID 11.7 :

* Tous les nœuds d'appliance StorageGRID sont automatiquement mis à niveau vers la version 3.7 du firmware du programme d'installation de l'appliance StorageGRID.
* Les appliances SG6060 et SGF6024 sont automatiquement mises à niveau vers la version du firmware du BIOS 3B07.EX et la version 3.97.07 du firmware du contrôleur BMC.
* Les appliances SG100 et SG1000 sont automatiquement mises à niveau vers la version 3B12.EC du firmware du BIOS et la version 4.71.07 du firmware du BMC.




== Il est possible que des alertes soient déclenchées

Des alertes peuvent être déclenchées lorsque les services démarrent et s'arrêtent, et lorsque le système StorageGRID fonctionne comme un environnement de version mixte (certains nœuds de grid exécutant une version antérieure, alors que d'autres ont été mis à niveau vers une version plus récente). D'autres alertes peuvent être déclenchées une fois la mise à niveau terminée.

Par exemple, vous pouvez voir l'alerte *Impossible de communiquer avec le nœud* lorsque les services sont arrêtés, ou vous pouvez voir l'alerte *Cassandra communication error* lorsque certains nœuds ont été mis à niveau vers StorageGRID 11.7 mais que d'autres nœuds exécutent encore StorageGRID 11.6. En général, ces alertes s'efface une fois la mise à niveau terminée.

L'alerte *ILM placement unatteignable* peut être déclenchée lorsque les nœuds de stockage sont arrêtés lors de la mise à niveau vers StorageGRID 11.7. Cette alerte peut persister 1 jour après la fin de la mise à niveau.

Une fois la mise à niveau terminée, vous pouvez consulter toutes les alertes liées à la mise à niveau en sélectionnant *alertes récemment résolues* ou *alertes actuelles* dans le tableau de bord de Grid Manager.



== De nombreuses notifications SNMP sont générées

Notez que de nombreuses notifications SNMP peuvent être générées lorsque les nœuds de la grille sont arrêtés et redémarrés lors de la mise à niveau. Pour éviter les notifications excessives, décochez la case *Activer les notifications d'agent SNMP* (*CONFIGURATION* > *surveillance* > *agent SNMP*) pour désactiver les notifications SNMP avant de démarrer la mise à niveau. Ensuite, réactivez les notifications une fois la mise à niveau terminée.



== Les modifications de configuration sont restreintes


NOTE: Cette liste s'applique spécifiquement aux mises à niveau de StorageGRID 11.6 vers StorageGRID 11.7. Si vous effectuez une mise à niveau vers une autre version de StorageGRID, reportez-vous à la liste des modifications restreintes dans les instructions de mise à niveau de cette version.

Jusqu'à la fin de la tâche *Activer la nouvelle fonction* :

* N'apportez aucune modification à la configuration de la grille.
* N'activez ou ne désactivez aucune nouvelle fonctionnalité. Par exemple, n'essayez pas de créer une connexion de fédération de grille tant que les deux systèmes StorageGRID n'ont pas été mis à jour vers StorageGRID 11.7.
* Ne mettez pas à jour la configuration ILM. Sinon, vous risquez d'avoir un comportement ILM incohérent et inattendu.
* N'appliquez pas de correctif ou ne restaurez pas de nœud de grille.
+

NOTE: Contactez le support technique si vous avez besoin de restaurer un nœud pendant la mise à niveau.

* Lors de la mise à niveau vers StorageGRID 11.7, vous ne devez pas gérer les groupes haute disponibilité, les interfaces VLAN ni les terminaux d'équilibrage de la charge.
* Ne supprimez aucun groupe haute disponibilité qu'une fois la mise à niveau vers StorageGRID 11.7 terminée. Les adresses IP virtuelles d'autres groupes haute disponibilité peuvent devenir inaccessibles.


Jusqu'à la fin de la tâche *étapes de mise à niveau finale* :

* N'effectuez pas de procédure d'extension.
* N'effectuez pas de procédure de mise hors service.




== Vous ne pouvez pas afficher les détails des compartiments ni gérer ces compartiments depuis le gestionnaire de locataires

Lors de la mise à niveau vers StorageGRID 11.7 (c'est-à-dire lorsque le système fonctionne comme un environnement à versions mixtes), vous ne pouvez pas afficher les détails des compartiments ni gérer les compartiments à l'aide du gestionnaire de locataires. L'une des erreurs suivantes apparaît sur la page compartiments du Gestionnaire de locataires :

* Vous ne pouvez pas utiliser cette API pendant la mise à niveau vers 11.7.
* Vous ne pouvez pas afficher les détails de la gestion des versions du compartiment dans le Gestionnaire de locataires pendant la mise à niveau vers la version 11.7.


Cette erreur se résoudra une fois la mise à niveau vers 11.7 terminée.

.Solution de contournement
Pendant la mise à niveau vers la version 11.7, utilisez les outils suivants pour afficher les détails des compartiments ou gérer les compartiments au lieu d'utiliser le gestionnaire de locataires :

* Pour effectuer des opérations S3 standard sur un compartiment, utilisez l'un ou l'autre link:../s3/operations-on-buckets.html["L'API REST S3"] ou le link:../tenant/understanding-tenant-management-api.html["API de gestion des locataires"].
* Pour exécuter des opérations personnalisées StorageGRID sur un compartiment (par exemple, affichage et modification du niveau de cohérence du compartiment, activation ou désactivation des mises à jour du dernier accès ou configuration de l'intégration de la recherche), utilisez l'API de gestion des locataires.




== Le chiffrement TLS ou les configurations SSH peuvent changer

Si le chiffrement TLS ou les configurations SSH ont été modifiés manuellement ou sont incohérents sur l'ensemble des nœuds, tous les nœuds seront remplacés par des modèles de compatibilité héritée ou moderne après la mise à niveau. Si vous avez utilisé `fips-ciphers.sh` Dans StorageGRID 11.6, la règle critères communs est appliquée à tous les nœuds. Dans le cas contraire, la stratégie de compatibilité héritée est appliquée. Si vous avez besoin de configurations validées par critères communs, vous devez utiliser la règle critères communs ou la règle stricte FIPS. Si vous n'avez pas utilisé `fips-ciphers.sh`, Vous devez utiliser le nouveau paramètre de compatibilité moderne une fois la mise à niveau terminée. Pour configurer les chiffrements, accédez à *CONFIGURATION* > *sécurité* > *Paramètres de sécurité* et sélectionnez *règles TLS et SSH*.



== Les ports CLB peuvent être convertis en terminaux d'équilibrage de charge

Le service CLB (Connection Load Balancer) hérité a été supprimé dans StorageGRID 11.7. Si la configuration CLB est détectée pendant les précontrôles de mise à niveau, l'alerte *activité d'équilibreur de charge CLB héritée détectée* est déclenchée. Si des certificats personnalisés ont été configurés pour l'API S3 ou Swift dans la version StorageGRID existante, les ports CLB 8082, 8083, 8084 et 8085 seront convertis en terminaux d'équilibrage de charge lors de la mise à niveau vers StorageGRID 11.7.

Voir aussi link:../admin/managing-load-balancing.html["Considérations relatives à l'équilibrage de charge"].
