---
permalink: ubuntu/index.html 
sidebar: sidebar 
keywords: about ubuntu, ubuntu overview 
summary: 'L"installation d"un système StorageGRID dans un environnement Ubuntu ou Debian comprend trois étapes principales.' 
---
= Installer Ubuntu ou Debian: Présentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'installation d'un système StorageGRID dans un environnement Ubuntu ou Debian comprend trois étapes principales.

. *Préparation*: Pendant la planification et la préparation, vous effectuez les tâches suivantes :
+
** En savoir plus sur les besoins matériels et de stockage pour StorageGRID.
** Découvrez les détails de link:../network/index.html["La mise en réseau StorageGRID"] vous pouvez ainsi configurer votre réseau de façon appropriée.
** Identifiez et préparez les serveurs physiques ou virtuels que vous prévoyez d'utiliser pour héberger vos nœuds de grid StorageGRID.
** Sur les serveurs que vous avez préparés :
+
*** Installez Linux
*** Configurez le réseau hôte
*** Configurer le stockage de l'hôte
*** Installez Docker
*** Installez les services d'hôte StorageGRID




. *Déploiement* : déployez des nœuds de la grille à l'aide de l'interface utilisateur appropriée. Lorsque vous déployez des nœuds grid, ils sont créés dans le cadre du système StorageGRID et connectés à un ou plusieurs réseaux.
+
.. Utilisez les fichiers de configuration de ligne de commande et de nœud Linux pour déployer des nœuds de grille virtuelle sur les hôtes que vous avez préparés à l'étape 1.
.. Utilisez le programme d'installation de l'appliance StorageGRID pour déployer les nœuds d'appliance StorageGRID.
+

NOTE: Les instructions d'installation et d'intégration spécifiques au matériel ne sont pas incluses dans la procédure d'installation de StorageGRID. Pour savoir comment installer les appliances StorageGRID, consultez le link:../installconfig/index.html["Démarrage rapide pour l'installation du matériel"] pour trouver les instructions relatives à votre appareil.



. *Configuration* : lorsque tous les nœuds ont été déployés, utilisez le gestionnaire de grille pour configurer la grille et terminer l'installation.


Ces instructions recommandent une approche standard pour le déploiement et la configuration d'un système StorageGRID dans un environnement Ubuntu ou Debian. Voir également les informations sur les approches alternatives suivantes :

* Utilisez une structure d'orchestration standard telle qu'Ansible, Puppet ou Chef pour installer Ubuntu ou Debian, configurer la mise en réseau et le stockage, installer Docker et le service hôte StorageGRID, et déployer des nœuds de grid virtuel.
* Automatiser le déploiement et la configuration du système StorageGRID à l'aide d'un script de configuration Python (fourni dans l'archive d'installation).
* Automatisez le déploiement et la configuration des nœuds grid d'appliance avec un script de configuration Python (disponible dans l'archive de l'installation ou depuis le programme d'installation de l'appliance StorageGRID).
* Si vous êtes un développeur avancé de déploiements StorageGRID, utilisez les API REST d'installation pour automatiser l'installation des nœuds grid d'StorageGRID.

