---
permalink: installconfig/viewing-error-codes-for-sg6000-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, error codes, errors, error, codes, sg6000-cn 
summary: 'Si une erreur matérielle se produit lors du démarrage du contrôleur SG6000-CN, le contrôleur BMC consigne un code d"erreur. Si nécessaire, vous pouvez afficher ces codes d"erreur à l"aide de l"interface BMC, puis travailler avec le support technique pour résoudre le problème.' 
---
= Afficher les codes d'erreur (contrôleur SG6000-CN)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si une erreur matérielle se produit lors du démarrage du contrôleur SG6000-CN, le contrôleur BMC consigne un code d'erreur. Si nécessaire, vous pouvez afficher ces codes d'erreur à l'aide de l'interface BMC, puis travailler avec le support technique pour résoudre le problème.

.Avant de commencer
* Vous savez comment accéder au tableau de bord BMC.


.Étapes
. Dans le tableau de bord BMC, sélectionnez *Code POST BIOS*.
. Passez en revue les informations affichées pour le code actuel et le code précédent.
+
Si l'un des codes d'erreur suivants s'affiche, contactez le support technique pour résoudre le problème.

+
[cols="1a,3a"]
|===
| Code | Indique 


 a| 
0x0E
 a| 
Microcode introuvable



 a| 
0x0F
 a| 
Microcode non chargé



 a| 
0x50
 a| 
Erreur d'initialisation de la mémoire. Type de mémoire non valide ou vitesse de mémoire incompatible.



 a| 
0x51
 a| 
Erreur d'initialisation de la mémoire. Échec de la lecture du démon du processeur de service.



 a| 
0x52
 a| 
Erreur d'initialisation de la mémoire. La taille de la mémoire n'est pas valide ou les modules de mémoire ne correspondent pas.



 a| 
0x53
 a| 
Erreur d'initialisation de la mémoire. Aucune mémoire utilisable détectée.



 a| 
0x54
 a| 
Erreur d'initialisation de la mémoire non spécifiée



 a| 
0x55
 a| 
Mémoire non installée



 a| 
0x56
 a| 
Type de CPU ou vitesse non valide



 a| 
0x57
 a| 
Non-concordance du processeur



 a| 
0x58
 a| 
Échec de l'autotest de la CPU ou erreur possible du cache de la CPU



 a| 
0x59
 a| 
Le micro-code de l'UC est introuvable ou la mise à jour du micro-code a échoué



 a| 
0x5A
 a| 
Erreur interne de l'UC



 a| 
0x5B
 a| 
La réinitialisation PPI n'est pas disponible



 a| 
0x5C
 a| 
Échec de l'autotest du BMC de phase PEI



 a| 
0xd0
 a| 
Erreur d'initialisation de l'UC



 a| 
0xD1
 a| 
Erreur d'initialisation du pont Nord



 a| 
0xD2
 a| 
Erreur d'initialisation du pont Sud



 a| 
0xd3
 a| 
Certains protocoles architecturaux ne sont pas disponibles



 a| 
0xD4
 a| 
Erreur d'allocation de ressources PCI. Manque de ressources.



 a| 
0xD5
 a| 
Pas d'espace pour la ROM optionnelle héritée



 a| 
0xD6
 a| 
Aucun périphérique de sortie de console n'a été trouvé



 a| 
0xD7
 a| 
Aucun périphérique d'entrée de console n'a été trouvé



 a| 
0xD8
 a| 
Mot de passe non valide



 a| 
0xD9
 a| 
Erreur lors du chargement de l'option d'amorçage (erreur Loadimage renvoyée)



 a| 
0xDA
 a| 
Échec de l'option de démarrage (erreur StartImage renvoyée)



 a| 
0xDB
 a| 
Échec de la mise à jour flash



 a| 
0xDC
 a| 
Le protocole de réinitialisation n'est pas disponible



 a| 
0xDD
 a| 
Échec de l'autotest du BMC de phase DXE



 a| 
0xE8
 a| 
MRC : ERR_NO_MEMORY



 a| 
0xE9
 a| 
MRC : ERR_LT_LOCK



 a| 
0xEA
 a| 
MRC : ERR_DDR_INIT



 a| 
0xEB
 a| 
MRC : ERR_MEM_TEST



 a| 
0xEC
 a| 
MRC : SPÉCIFIQUE À ERR_VENDOR



 a| 
0xED
 a| 
MRC : ERR_DIMM_COMPAT



 a| 
0xEE
 a| 
MRC : COMPATIBILITÉ ERR_MRC



 a| 
0xEF
 a| 
MRC : ERR_MRC_STRUCT



 a| 
0xF0
 a| 
MRC : ERR_SET_VDD



 a| 
0xF1
 a| 
MRC : ERR_IOT_MEM_BUFFER



 a| 
0xF2
 a| 
MRC : ERR_RC_INTERNAL



 a| 
0xF3
 a| 
MRC : ERR_INVALID_REG_ACCESS



 a| 
0xF4
 a| 
MRC : ERR_SET_MC_FREQ



 a| 
0xF5
 a| 
MRC : ERR_READ_MC_FREQ



 a| 
0x70
 a| 
MRC : ERR_DIMM_CHANNEL



 a| 
0x74
 a| 
MRC : ERR_BIST_CHECK



 a| 
0xF6
 a| 
MRC : ERR_SMBUS



 a| 
0xF7
 a| 
MRC : ERR_PCU



 a| 
0xF8
 a| 
MRC : ERR_NGN



 a| 
0xF9
 a| 
MRC : ERR_INTERLEAVE_FAILURE

|===

