---
permalink: tenant/viewing-s3-bucket-details.html 
sidebar: sidebar 
keywords: how to view bucket details 
summary: Vous pouvez afficher les compartiments de votre compte de locataire. 
---
= Afficher les détails du compartiment
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les compartiments de votre compte de locataire.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de locataires à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].


.Étapes
. Sélectionnez *Afficher les compartiments* dans le tableau de bord ou sélectionnez *STOCKAGE (S3)* > *compartiments*.
+
La page compartiments s'affiche.

. Passez en revue les informations récapitulatives pour chaque compartiment.
+
Si nécessaire, vous pouvez trier les informations par colonne, ou vous pouvez avancer et revenir à la liste.

+

IMPORTANT: Les valeurs nombre d'objets et espace utilisé affichées sont des estimations. Ces estimations sont affectées par le moment de l'ingestion, la connectivité réseau et l'état des nœuds. Si la gestion des versions des compartiments est activée, les versions des objets supprimés sont incluses dans le nombre d'objets.

+
[cols="1a,3a"]
|===
| Colonne | Description 


 a| 
Nom
 a| 
Nom unique du compartiment, qui ne peut pas être modifié.



 a| 
Fonctionnalités activées
 a| 
Liste des fonctions activées pour le compartiment.



 a| 
Verrouillage d'objet S3
 a| 
Indique si le verrouillage d'objet S3 est activé pour le compartiment.

Cette colonne apparaît uniquement si le verrouillage objet S3 est activé pour la grille. Cette colonne affiche également des informations pour tous les compartiments conformes existants.



 a| 
Région
 a| 
La région du compartiment, qui ne peut pas être modifiée.



 a| 
Nombre d'objets
 a| 
Nombre d'objets dans ce compartiment. Lorsque des objets sont ajoutés ou supprimés, il est possible que cette valeur ne soit pas mise à jour immédiatement. Si la gestion des versions des compartiments est activée, les versions d'objets non actuelles sont incluses dans cette valeur.



 a| 
Espace utilisé
 a| 
Taille logique de tous les objets du compartiment. La taille logique n'inclut pas l'espace réel requis pour les copies répliquées ou avec code d'effacement, ni pour les métadonnées d'objet.



 a| 
Date de création
 a| 
Date et heure de création du compartiment.

|===
. Pour afficher les détails d'un compartiment spécifique, sélectionnez le nom du compartiment dans le tableau.
+
La page des détails du compartiment s'affiche. À partir de cette page, vous pouvez effectuer les tâches suivantes :

+
** Configurez et gérez des options de compartiment, notamment link:changing-consistency-level.html["niveau de cohérence"], link:enabling-or-disabling-last-access-time-updates.html["mises à jour de l'heure du dernier accès"], link:changing-bucket-versioning.html["gestion des versions d'objets"], link:using-s3-object-lock.html["Verrouillage d'objet S3"] et link:update-default-retention-settings.html["rétention de compartiments par défaut"]
** Configurez l'accès au compartiment, par exemple link:configuring-cross-origin-resource-sharing-cors.html["Partage des ressources d'origine croisée (CORS)"]
** Gérez link:what-platform-services-are.html["services de plateforme"] (si autorisé pour le locataire), y compris la réplication, les notifications d'événements et l'intégration de la recherche
** Activer et link:grid-federation-manage-cross-grid-replication.html["gérer la réplication entre les grilles"] (Si le locataire est autorisé) pour répliquer les objets ingérés dans ce compartiment vers un autre système StorageGRID
** Accédez au link:use-s3-console.html["Console S3 expérimentale"] pour gérer les objets dans le compartiment
** link:deleting-s3-bucket-objects.html["Supprime tous les objets d'un compartiment"]
** link:deleting-s3-bucket.html["Supprimer un compartiment"] c'est déjà vide



