---
permalink: vmware/required-materials.html 
sidebar: sidebar 
keywords: installation materials vmware 
summary: 'Avant d"installer StorageGRID, vous devez rassembler et préparer les ressources nécessaires.' 
---
= Matériel requis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer StorageGRID, vous devez rassembler et préparer les ressources nécessaires.

[cols="1a,2a"]
|===
| Élément | Remarques 


 a| 
Licence NetApp StorageGRID
 a| 
Vous devez disposer d'une licence NetApp valide et signée numériquement.

*Remarque* : l'archive d'installation de StorageGRID inclut une licence gratuite qui ne fournit aucun droit de support pour le produit.



 a| 
Archive de l'installation de StorageGRID
 a| 
Vous devez link:downloading-and-extracting-storagegrid-installation-files.html["Téléchargez l'archive d'installation de StorageGRID et extrayez les fichiers"].



 a| 
Le logiciel et la documentation VMware
 a| 
Lors de l'installation, vous utilisez le client Web VMware vSphere pour déployer des nœuds grid virtuels sur des machines virtuelles. Pour les versions prises en charge, reportez-vous à la section https://["Matrice d'interopérabilité NetApp"^].



 a| 
L'ordinateur portable de service
 a| 
Le système StorageGRID est installé par le biais d'un service après-vente. L'ordinateur portable de service doit posséder :

* Port réseau
* Client SSH (par exemple, PuTTY)
* link:../admin/web-browser-requirements.html["Navigateur Web pris en charge"]




 a| 
Documentation StorageGRID
 a| 
* link:../release-notes/index.html["Notes de mise à jour"]
* link:../admin/index.html["Instructions d'administration de StorageGRID"]


|===