---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, post object restore, object 
summary: Vous pouvez utiliser la demande de restauration POST-objet S3 pour restaurer un objet stocké dans un pool de stockage cloud. 
---
= Restauration POST-objet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la demande de restauration POST-objet S3 pour restaurer un objet stocké dans un pool de stockage cloud.



== Type de demande pris en charge

StorageGRID ne prend en charge que les demandes DE restauration POST-objet pour restaurer un objet. Elle ne prend pas en charge le `SELECT` type de restauration. Sélectionnez demandes de retour `XNotImplemented`.



== Gestion des versions

Spécifiez éventuellement `versionId` pour restaurer une version spécifique d'un objet dans un compartiment multiversion. Si vous ne spécifiez pas `versionId`, la version la plus récente de l'objet est restaurée



== Comportement de restauration POST-objet sur les objets de pool de stockage cloud

Si un objet a été stocké dans un pool de stockage cloud (voir les instructions de gestion des objets avec gestion du cycle de vie des informations), une demande de restauration POST-objet présente le comportement suivant, en fonction de l'état de l'objet. Voir « objet TÊTE » pour plus de détails.


NOTE: Si un objet est stocké dans un pool de stockage cloud et qu'une ou plusieurs copies de cet objet existent également dans la grille, il n'est pas nécessaire de le restaurer en émettant une demande de restauration POST-objet. En revanche, la copie locale peut être récupérée directement à l'aide d'une demande D'OBJET GET.

[cols="1a,2a"]
|===
| État de l'objet | Comportement de la restauration POST-objet 


 a| 
L'objet est ingéré dans StorageGRID mais pas encore évalué par ILM ou l'objet ne se trouve pas dans un pool de stockage cloud
 a| 
`403 Forbidden`, `InvalidObjectState`



 a| 
Objet dans Cloud Storage Pool, mais pas encore migré vers un état non récupérable
 a| 
`200 OK` Aucune modification n'est apportée.

*Remarque* : avant qu'un objet ne soit transféré à un état non récupérable, vous ne pouvez pas le modifier `expiry-date`.



 a| 
L'objet a été transféré à un état non récupérable
 a| 
`202 Accepted` Restaure une copie récupérable de l'objet vers le pool de stockage cloud pendant le nombre de jours spécifié dans le corps de la demande. À la fin de cette période, l'objet est renvoyé à un état non récupérable.

Si vous le souhaitez, utilisez le `Tier` elément de demande pour déterminer la durée de la tâche de restauration (`Expedited`, `Standard`, ou `Bulk`). Si vous ne spécifiez pas `Tier`, le `Standard` le niveau est utilisé.

*Important* : si un objet a été transféré vers S3 Glacier Deep Archive ou si le pool de stockage cloud utilise le stockage Azure Blob, vous ne pouvez pas le restaurer à l'aide du `Expedited` niveau. L'erreur suivante est renvoyée `403 Forbidden`, `InvalidTier`: `Retrieval option is not supported by this storage class`.



 a| 
Objet en cours de restauration à partir d'un état non récupérable
 a| 
`409 Conflict`, `RestoreAlreadyInProgress`



 a| 
Objet entièrement restauré dans le pool de stockage cloud
 a| 
`200 OK`

*Remarque :* si un objet a été restauré à un état récupérable, vous pouvez le modifier `expiry-date` En réémettant la demande DE restauration POST Object avec une nouvelle valeur pour `Days`. La date de restauration est mise à jour par rapport à l'heure de la demande.

|===
.Informations associées
link:../ilm/index.html["Gestion des objets avec ILM"]

link:head-object.html["Objet TÊTE"]

link:s3-operations-tracked-in-audit-logs.html["Opérations S3 suivies dans les journaux d'audit"]
