---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 upload part operation 
summary: 'L"opération de téléchargement de pièce télécharge une pièce dans un téléchargement partitionné pour un objet.' 
---
= Télécharger la pièce
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'opération de téléchargement de pièce télécharge une pièce dans un téléchargement partitionné pour un objet.



== En-têtes de demande pris en charge

Les en-têtes de requête suivants sont pris en charge :

* `Content-Length`
* `Content-MD5`




== Demander des en-têtes pour le cryptage côté serveur

Si vous avez spécifié le cryptage SSE-C pour lancer la demande de téléchargement multipièce, vous devez également inclure les en-têtes de requête suivants dans chaque demande de chargement de pièce :

* `x-amz-server-side-encryption-customer-algorithm`: Spécifiez `AES256`.
* `x-amz-server-side-encryption-customer-key`: Spécifiez la même clé de cryptage que celle que vous avez fournie dans la demande de lancement de Multipart Upload.
* `x-amz-server-side-encryption-customer-key-MD5`: Spécifiez le même résumé MD5 que vous avez fourni dans la demande de lancement de Multipart Upload.



IMPORTANT: Les clés de chiffrement que vous fournissez ne sont jamais stockées. Si vous perdez une clé de chiffrement, vous perdez l'objet correspondant. Avant d'utiliser les clés fournies par le client pour sécuriser les données d'objet, consultez les considérations de la section « utilisation du cryptage côté serveur ».



== Gestion des versions

Le téléchargement partitionné est constitué de différentes opérations permettant de lancer le téléchargement, de répertorier les téléchargements, de télécharger des pièces, d'assembler les pièces téléchargées et de terminer le téléchargement. Les objets sont créés (et versionnés le cas échéant) lorsque l'opération de chargement multipièce complète est exécutée.

.Informations associées
link:using-server-side-encryption.html["Utilisez le cryptage côté serveur"]
