---
permalink: maintain/index.html 
sidebar: sidebar 
keywords: maintain overview, maintenance overview, about maintain, about maintenance 
summary: Suivez ces instructions pour entretenir votre système StorageGRID et effectuer une reprise après incident. 
---
= Restauration et maintenance : vue d'ensemble
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces instructions pour entretenir votre système StorageGRID et effectuer une reprise après incident.



== À propos de ces instructions

Ces instructions expliquent comment appliquer un correctif logiciel, récupérer des nœuds de la grille, récupérer un site défaillant, désaffecter des nœuds de la grille ou un site entier, effectuer la maintenance du réseau, exécuter des procédures de maintenance au niveau de l'hôte et du middleware et exécuter des procédures de nœud de la grille.


NOTE: Dans ces instructions, « Linux » fait référence à un déploiement Red Hat® Enterprise Linux®, Ubuntu®, CentOS ou Debian®. Utilisez le https://["Matrice d'interopérabilité NetApp"^] pour obtenir une liste des versions prises en charge.



== Avant de commencer

* Vous avez une bonne compréhension du système StorageGRID.
* Vous avez examiné la topologie de votre système StorageGRID et compris la configuration de la grille.
* Vous comprenez que vous devez suivre toutes les instructions exactement et tenir compte de tous les avertissements.
* Vous comprenez que les procédures de maintenance non décrites ne sont pas prises en charge ou requièrent une mission de service.




== Procédures de maintenance des appareils

Pour connaître les procédures matérielles, reportez-vous aux instructions de maintenance de votre appliance StorageGRID.

* link:../sg6100/index.html["Maintenance de l'appliance SGF6112"]
* link:../sg100-1000/index.html["Maintenance des appliances SG100 et SG1000"]
* link:../sg6000/index.html["Entretenir l'appareil SG6000"]
* link:../sg5700/index.html["Conservez l'appliance SG5700"]

