---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html 
sidebar: sidebar 
keywords: grid node, add node, add site, expand, expansion 
summary: 'Vous pouvez suivre cette procédure pour ajouter des nœuds de grille à des sites existants ou pour ajouter un nouveau site, mais vous ne pouvez pas effectuer les deux types d"extension en même temps.' 
---
= Ajout de nœuds grid à un site existant ou ajout d'un site
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez suivre cette procédure pour ajouter des nœuds de grille à des sites existants ou pour ajouter un nouveau site, mais vous ne pouvez pas effectuer les deux types d'extension en même temps.

.Avant de commencer
* Vous disposez de l'autorisation accès racine ou Maintenance.
* Tous les nœuds existants de la grille sont opérationnels sur tous les sites.
* Toute procédure d'extension, de mise à niveau, de déclassement ou de restauration est terminée.
+

NOTE: Vous ne pouvez pas démarrer une extension pendant qu'une autre procédure d'extension, de mise à niveau, de récupération ou de mise hors service active est en cours. Toutefois, si nécessaire, vous pouvez interrompre une procédure de mise hors service pour démarrer une extension.



.Étapes
. link:updating-subnets-for-grid-network.html["Mise à jour des sous-réseaux pour le réseau Grid"].
. link:deploying-new-grid-nodes.html["Déploiement de nouveaux nœuds grid"].
. link:performing-expansion.html["Réaliser une extension"].

