---
permalink: expand/contacting-technical-support.html 
sidebar: sidebar 
keywords: contact technical support 
summary: 'Si vous rencontrez des erreurs lors du processus d"extension de la grille que vous ne parvenez pas à résoudre ou si une tâche de grille échoue, contactez le support technique.' 
---
= Contactez l'assistance technique
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous rencontrez des erreurs lors du processus d'extension de la grille que vous ne parvenez pas à résoudre ou si une tâche de grille échoue, contactez le support technique.

.Description de la tâche
Lorsque vous contactez le support technique, vous devez fournir les fichiers journaux requis pour vous aider à résoudre les erreurs que vous rencontrez.

.Étapes
. Se connecter au nœud d'extension qui a rencontré des défaillances :
+
.. Saisissez la commande suivante :``ssh -p 8022 admin@_grid_node_IP_``
+

NOTE: Le port 8022 est le port SSH du système d'exploitation de base, tandis que le port 22 est le port SSH du moteur de mise en conteneurs exécutant StorageGRID.

.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.


+
Une fois que vous êtes connecté en tant que root, l'invite passe de `$` à `#`.

. En fonction de la phase d'installation atteinte, récupérez l'un des journaux suivants disponibles sur le nœud de la grille :
+
[cols="1a,2a"]
|===
| Plateforme | Journaux 


 a| 
VMware
 a| 
** `/var/log/daemon.log`
** `/var/log/storagegrid/daemon.log`
** `/var/log/storagegrid/nodes/<node-name>.log`




 a| 
Linux
 a| 
** `/var/log/storagegrid/daemon.log`
** `/etc/storagegrid/nodes/<node-name>.conf` (pour chaque nœud défaillant)
** `/var/log/storagegrid/nodes/<node-name>.log` (pour chaque nœud en panne ; il se peut qu'il n'existe pas)


|===

