---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 'Après avoir ajouté des nœuds de stockage, vous pouvez utiliser la procédure de rééquilibrage EC pour redistribuer les fragments avec code d"effacement entre les nœuds de stockage existants et nouveaux.' 
---
= Rééquilibrent les données codées après l'ajout de nœuds de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir ajouté des nœuds de stockage, vous pouvez utiliser la procédure de rééquilibrage EC pour redistribuer les fragments avec code d'effacement entre les nœuds de stockage existants et nouveaux.

.Avant de commencer
* Vous avez terminé les étapes d'extension pour ajouter les nouveaux nœuds de stockage.
* Vous avez passé en revue le link:considerations-for-rebalancing-erasure-coded-data.html["considérations relatives au rééquilibrage des données avec code d'effacement"].
* Vous comprenez que les données d'objet répliqué ne seront pas déplacées par cette procédure et que la procédure de rééquilibrage EC ne tient pas compte de l'utilisation des données répliquées sur chaque nœud de stockage lors de la détermination de l'emplacement du déplacement des données codées par l'effacement.
* Vous avez le `Passwords.txt` fichier.


.Que se passe-t-il lorsque cette procédure est exécutée
Avant de commencer la procédure, noter les points suivants :

* La procédure de rééquilibrage EC ne démarre pas si un ou plusieurs volumes sont hors ligne (démontés) ou s'ils sont en ligne (montés) mais en état d'erreur.
* La procédure de rééquilibrage EC réserve temporairement une grande quantité de stockage. Les alertes de stockage peuvent être déclenchées, mais elles seront résolus une fois le rééquilibrage terminé. S'il n'y a pas assez de stockage pour la réservation, la procédure de rééquilibrage EC échoue. Les réservations de stockage sont libérées lorsque la procédure de rééquilibrage EC est terminée, que la procédure ait échoué ou a réussi.
* Si un volume passe hors ligne ou rencontre une erreur pendant le rééquilibrage du code d'effacement, le processus de rééquilibrage se termine partiellement, sans perte de données. La procédure de rééquilibrage EC peut être reprise au point où elle s'est arrêtée lorsque tous les volumes sont en ligne sans erreur.
* L'exécution de la procédure de rééquilibrage EC peut avoir un impact sur les performances des opérations ILM et des opérations clients S3 et Swift.
+

NOTE: Si le processus de rééquilibrage EC prend plus de 24 heures, les opérations des API S3 et Swift pour charger des objets (ou des pièces d'objet) peuvent échouer. Les opérations PUT de longue durée échouent si la règle ILM applicable utilise un placement équilibré ou strict à l'entrée. L'erreur suivante sera signalée : `500 Internal Server Error`.



.Étapes
. [[Review_Object_Storage]]consultez les détails actuels du stockage objet pour le site que vous prévoyez de rééquilibrer.
+
.. Sélectionnez *NOEUDS*.
.. Sélectionnez le premier nœud de stockage du site.
.. Sélectionnez l'onglet *stockage*.
.. Positionnez le curseur de votre souris sur le graphique stockage utilisé - données d'objet pour afficher la quantité actuelle de données répliquées et de données avec code d'effacement sur le nœud de stockage.
.. Répétez cette procédure pour afficher les autres nœuds de stockage du site.


. Connectez-vous au nœud d'administration principal :
+
.. Saisissez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Démarrer la procédure :
+
`rebalance-data start --site "_site-name_"`

+
Pour `"_site-name_"`, Spécifiez le premier site sur lequel vous avez ajouté un ou plusieurs nœuds de stockage. Entourez-la `site-name` entre guillemets.

+
La procédure de rééquilibrage EC démarre et un ID de tâche est renvoyé.

. Copier l'ID du travail.
. Surveiller le statut de la procédure de rééquilibrage EC.
+
** Pour afficher le statut d'une procédure de rééquilibrage EC unique :
+
`rebalance-data status --job-id _job-id_`

+
Pour `_job-id_`, Spécifiez l'ID renvoyé au début de la procédure.

** Pour afficher le statut de la procédure de rééquilibrage EC actuelle et toutes les procédures précédemment effectuées :
+
`rebalance-data status`

+
[NOTE]
====
Pour obtenir de l'aide sur la commande rééquilibrer-données :

`rebalance-data --help`

====


. Effectuer des étapes supplémentaires en fonction de l'état renvoyé :
+
** Si l'état est `In progress`, L'opération EC de rééquilibrage est toujours en cours. Vous devez régulièrement surveiller la procédure jusqu'à ce qu'elle soit terminée.
+
Pour afficher le temps d'achèvement estimé et le pourcentage d'achèvement de la tâche en cours :

+
... Sélectionnez *SUPPORT* > *Outils* > *métriques*.
... Sélectionnez *EC Overview* dans la section Grafana.
... Examinez les tableaux de bord *Grid EC Job estimé Time to Completion* et *Grid EC Job Percentage Finted*.


** Si l'état est `Success`, facultatif <<review_object_storage,examinez le stockage objet>> pour afficher les détails mis à jour pour le site.
+
Les données avec code d'effacement doivent désormais être plus équilibrées entre les nœuds de stockage du site.

+
[TIP]
====
Si le message suivant s'affiche, exécutez à nouveau la procédure de rééquilibrage de l'EC jusqu'à ce que toutes les données avec code d'effacement aient été rééquilibrées :

`The moves in this rebalance job have been limited. To rebalance additional data, start EC rebalance again for the same site.`

====
** Si l'état est `Failure`:
+
... Vérifiez que tous les nœuds de stockage du site sont connectés à la grille.
... Recherchez et résolvez les alertes susceptibles d'affecter ces nœuds de stockage.
... Relancez la procédure de rééquilibrage EC :
+
`rebalance-data start –-job-id _job-id_`

... Si le statut de la procédure de rééquilibrage de la ce est toujours `Failure`, contactez le support technique.




. Si la procédure de rééquilibrage EC génère une charge trop importante (par exemple, les opérations d'ingestion sont affectées), mettez la procédure en pause.
+
`rebalance-data pause --job-id _job-id_`

. Si vous devez terminer la procédure de rééquilibrage EC (par exemple, pour une mise à niveau logicielle StorageGRID), entrez ce qui suit :
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: Lorsque vous terminez une procédure de rééquilibrage EC, tout fragment de données qui a déjà été déplacé reste au nouvel emplacement. Les données ne sont pas retransférées à leur emplacement d'origine.

. Si vous utilisez le code d'effacement sur plusieurs sites, exécutez cette procédure pour tous les autres sites concernés.

